default_platform(:ios)

platform :ios do
  before_all do |lane, options|
    if is_ci
      ENV['MATCH_KEYCHAIN_NAME'] = 'TempKeychain'
      ENV['MATCH_KEYCHAIN_PASSWORD'] = 'TempKeychainPassword'
      create_keychain(
	      name: ENV["MATCH_KEYCHAIN_NAME"],
	      password: ENV["MATCH_KEYCHAIN_PASSWORD"],
	      timeout: 1800
	    )
    end
  end

  lane :build do
    match(readonly: is_ci)

    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      team_id: ENV["sigh_com.oke331.flutterCicd_adhoc_team-id"],
      profile_name: ENV["sigh_com.oke331.flutterCicd_adhoc_profile-name"]
    )

    increment_build_number(
      build_number: ENV["BUILD_NUMBER"]
    )

    gym()

    firebase_app_distribution(
        app: ENV["FIREBASE_IOS_APP_ID"],
        groups: "company",
        firebase_cli_token:  ENV["FIREBASE_APP_TOKEN"],
        release_notes: "ベータ版配信",
    )
  end
end