name: ios_cicd

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macOS-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name:  Translate secrets of base64 into json
        env:
            GOOGLE_SERVICE: ${{ secrets.IOS_GOOGLE_SERVICE_INFO }}
        run:
            echo $GOOGLE_SERVICE | base64 --decode > ./ios/Runner/output.json

      - name:  Translate json into plist and generate GoogleService-info.plist
        run:
          plutil -convert xml1 ./ios/Runner/output.json -o ./ios/Runner/GoogleService-info.plist

      - name: Remove json file
        run:
          rm ios/Runner/output.json

      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable'

      - name: Flutter setup
        run: |
          flutter pub get
          flutter test
          flutter build ios --release --no-codesign

      - name: build and app distribution
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          FIREBASE_IOS_APP_ID: ${{secrets.FIREBASE_IOS_APP_ID}}
          FIREBASE_APP_TOKEN:  ${{secrets.FIREBASE_APP_TOKEN}}
          BUILD_NUMBER:  $GITHUB_RUN_NUMBER
        run: |
          cd ios
          fastlane build